language: objective-c
osx_image: xcode7.2
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/CPImageViewer.mobileprovision.enc -d -a -out scripts/profile/CPImageViewer.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- "./scripts/add-key.sh"
script:
- xcodebuild -project CPImageViewer.xcodeproj -target CPImageViewer -sdk iphoneos -configuration Release OBJROOT="$PWD/build" SYMROOT="$PWD/build" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
after_script:
- "./scripts/remove-key.sh"
after_success:
- "./scripts/sign-and-upload.sh"
env:
  global:
  - APP_NAME="CPImageViewer"
  - 'DEVELOPER_NAME="iPhone Distribution: ZTE Software Changsha Co., Ltd"'
  - PROFILE_NAME="CPImageViewer"
  - PROVISIONING_PROFILE="$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_NAME.mobileprovision"
  - TRAVIS_BRANCH="master"
  - TRAVIS_BUILD_NUMBER="1.0.0"
  - INFO_PLIST="CPImageViewer/Info.plist"
  - BUNDLE_DISPLAY_NAME="CPImageViewer"
  - secure: dUb6mo0R6/E61c43oyHGDYvvGPBoe7fkXgIsLbSqFh+/v5DF1KWjtdXFn8RdlLjfUZMfwcz8eVYTDYMjg1Sku7b2JNbJg6vWCqhc1et6hwgtFo8vQrli9AlNEel7H74LVX264UGv/B98hBNZxsHE4tw5rjmhye6b4gE300WKDIt7moedPcaBfmBIwqZoT45BSD0YA8v0WotlUd+zNgwSQQcOB/XZFMeT55rRQiOEUsexnoeRiAVuFO5fug2IlaAaHyv4g6kl/hB4xaVWu/Gz1oOUTbL45xhYZBgFANH9fyr23Cml+yRC26dEAUuFsgLu0VQ+NZV0bboUv3O+nCFKENZoWYFfJroTd8fMMR0hDBNy324/U3IjCt7dic3zyj1lKjd6SyI8s8Pd7WP8WqLG71bRATvms8OynkRgpHDisO6ye/s6O/b5f67JCVjdkVhbxHTBZRYNMETCOcL5XBf/xzj4bu+QIr+8MCApaePgf75L2PvShHhzjto/cS+PxMKD+F1SfqjcFOKxDQo31t6M+7Xlmi88jMTR7Ga3k8aeqpd5B2SNhvt6LoakB+u9w2JPEzQbZxXKFfeVzQL6aEH95w5/Fw+G1io9DY2oaLGGHnlb5A8Q/Bx8YLpK6qv9i+do3uM2of0KHap5e2QoHbxKVvUVKy/o61E9idCEh2qNwbk=
  - secure: z6B5h1SDdXsFmzylgThptf77udVLhgT/Q895VTcWsCRrEYVm9h3g2IS5ure/HrpUuCK06KG1GAQI2L/pGyafgaayy10KOVtjUKBP+l2gQMKwGk6GaQmS64Bnlb1Wr8yJ7oPheYsuQc+97WachGXZPAKXlp0eHk07C9RuUfyODo86DOZGrPF99A9/N8qTGVNOfWu0XI0BhvKGFFfNCehhPqGEpeL8WI2mVMqlH71JXuOSM6riEr5dPmpZoCrNytBFjcmxBsfpwmsg1ymP5yTZEuM0TfFZxw9BEYIPH6+/GSgy3DAARlc1b3l31WozSElbaa6Qd9CpKRBB+WmcIvIp/OkrsBhzmh/eDAWfNEJx6N9wD3wbcGER7frZHGhWyCyUonpxgOn/+xgKWAvBd9GKdTboU3Q7A4qsKBLj0NrHJGChsa3M/OTohXSiqDAIk+KtV+3SyMPTwi2mHoojg6ejd+FFiGu/3Uq+x6kUp5KPAUUU+w+5n9KL8Av5qpa1a6tOye7lP/Gs1xv2OeXmLwWg4NHMWrx0ANoi/b0hFVTDGD+CgcXE1NzTRW/WM8FJpKh03n9h/kxm6kDZnjsGQ9vbLmwi7eJ00WVJAjxrB4KrGMIqqq9JSxvlOqn/BaHR/nhS/f7bmnrkVYa3huhegsWBq2lpaWARpBcaklZhF2Ex7Og=
